### ISSUE TITLE
Set up SCSS build

### ISSUE THREAD

**Issue by Charlotteis** [yourfirstpr/yourfirstpr.github.io#1]
I would like this repository to use SCSS.

The way I would like this to act:
* I work on this github project locally
* I write in a .scss file
* Every time the .scss changes (on save of the file), compile the css and add it to style.css which will act as the main style for the site.

**Comment by nickcolley** [comment]
Do we need a pre-processor for this? Could just write pure CSS.

**Comment by Charlotteis** [comment]
@nickcolley My reasons for using SCSS are: bleh, it's just what I'm used to.
I didn't put a whole lot of thought into it! However, I do want to minify our CSS using a build script or what have you, so I will create a new issue for that. Thank you :)
