### ISSUE TITLE
LibFalcon - Simple C library for Hobby OS Kernels

### ISSUE THREAD

**Issue by hatlesshacker** [yourfirstpr/yourfirstpr.github.io#101]
https://github.com/Zefyer/LibFalcon

Most routines required by simple hobbyist kernels are provided here, however A LOT of functions are not yet implemented. Help is required for implementing Math-functions and documentation.
Looking forward to working with interested developers!

**Comment by jcc5225** [comment]
I'm interested in contributing to your project. What kind of math functions did you have in mind?

**Comment by hatlesshacker** [comment]
Heyya jcc5225! 
Take a peek at the code, you'll find that functions like abs(), ldiv(), sqrt() are not there. Would be great if you do something about it! :100:
