### ISSUE TITLE
GitHub pages for organization use the master branch

### ISSUE THREAD

**Issue by hugovk** [yourfirstpr/yourfirstpr.github.io#14]
> **User & Organization Pages** live in a special repository dedicated to GitHub Pages files. You will need to name this repository with the account name.

> * You must use the `username.github.io` naming scheme.
> * Content from the `master` branch will be used to build and publish your GitHub Pages site.

https://help.github.com/articles/user-organization-and-project-pages/

*Project Pages* are the ones that use the `gh-pages` branch. This isn't a project page.

1. A PR is needed to merge the `gh-pages` branch into the `master` branch.

2. The repo owner can then set the `master` branch as the default branch here:
https://github.com/yourfirstpr/yourfirstpr.github.io/settings/branches

3. The repo owner can then remove the superfluous `gh-pages` branch here:
https://github.com/yourfirstpr/yourfirstpr.github.io/branches

**Comment by Charlotteis** [comment]
@hugovk Thanks hugo, I'm so used to doing project pages that I completely missed this. Will fix when i can! Good to know this before I started to build the actual website :D

**Comment by Charlotteis** [comment]
Thank you @hugovk, I've done this now :)
