### ISSUE TITLE
Article link giving 404 error

### ISSUE THREAD

**Issue by rjsu26** [yourfirstpr/yourfirstpr.github.io#160]
### The article "First Timers Only" is showing 404 error after being redirected on Medium.
Relevant snapshots are shown below

![image](https://user-images.githubusercontent.com/32229344/60773639-ffdc4b80-a125-11e9-8a38-9be2a0c539c9.png)

![image](https://user-images.githubusercontent.com/32229344/60773654-36b26180-a126-11e9-84dc-5e15fa5c7003.png)

**Comment by vineeth-krishnan** [comment]
**Replace**  the hyperlink (*First Timers Only*) with
https://kentcdodds.com/blog/first-timers-only/

**Comment by fboechats** [comment]
Just solved that issue: https://github.com/yourfirstpr/yourfirstpr.github.io/pull/161
