### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by Charlotteis** [yourfirstpr/yourfirstpr.github.io#3]
Let's get a logo! Branding! Magic! For use on Twitter and other websites using a display picture (like GitHub)

I do not expect high quality, vectored, rastered, magical creations. Just have fun.
If you are able to incorporate this colour into it, that'd be magical! #9266CC (purple).

Any time is appreciated, you are wonderful.

**Comment by Charlotteis** [comment]
If you do create a logo for this, I will make stickers and send you some!

**Comment by pdurbin** [comment]
I dropped a link in #opensourcedesign on freenode in the hopes that someone from @opensourcedesign gets interested: https://botbot.me/freenode/opensourcedesign/msg/49110669/

I heard about @yourfirstpr in the @openhatch IRC channel (thanks, @ehashman!): http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-09-06#i_3701629

**Comment by Charlotteis** [comment]
Hello @pdurbin, thanks! Very much appreciated :)
Lovely to see people talk about yourfirstpr :hand:

**Comment by YiyiZhang** [comment]
hi! I just made a couple for fun - very sorry if I didn't do the pull request correctly (am a github novice)

**Comment by Charlotteis** [comment]
Hi @YiyiZhang! I replied on your PR, thank you for submitting one.

I would like to leave this open for other submissions as I'd like to let other people have a go, but these are fantastic.

**Comment by YiyiZhang** [comment]
Awesome, saw the reply - thanks!

**Comment by fredericmarx** [comment]
I also had a few ideas. Feel free to comment. Can send AIs/SVGs if wanted.

**Comment by diptajbasu** [comment]
Hi @Charlotteis!
Sending in a PR for a logo concept. Hope it's useful and happy to iterate on it.

Cheers!
![djb_logo](https://cloud.githubusercontent.com/assets/7990216/10867147/cc34a9a6-8029-11e5-81cb-4f212d0036b8.png)
