### ISSUE TITLE
Display a list of the YFPR tweets on the main page

### ISSUE THREAD

**Issue by Charlotteis** [yourfirstpr/yourfirstpr.github.io#30]
Using the Twitter API
- Not replies
- Only ones with GitHub links in them

**Comment by jk16** [comment]
Hey how can i work on this?

**Comment by Charlotteis** [comment]
Hey @jk16. It's actually not possible to work on it right now as the Twitter API requires OAuth/Server Side authentication and this is just a static website hosted on GitHub. If we ever move to our own server (fairly unlikely in the short-term) then we can try and do this. Sorry about that! When I wrote the issue I didn't know that the Twitter API worked in that way.

**Comment by Charlotteis** [comment]
I'll reopen this when we finally move away from GitHub pages?
