### ISSUE TITLE
Set up blog posts with Jekyll

### ISSUE THREAD

**Issue by Charlotteis** [yourfirstpr/yourfirstpr.github.io#31]
So we can write guides for being an awesome contributor and maintainer, as well as news and updates about Your First PR and it's events.

**Comment by brad-j** [comment]
Hi! I'd love to work on this as my first PR.

From what I understand, you want to set up a blog for yourfirstpr.github.io right? Any Ideas of how you would like the posts to be displayed?  

Also, I don't really know what needs-better-explination means. Can you shed a little light on this?

Thanks!

**Comment by Charlotteis** [comment]
Hi brad!
So this website is built using [Jekyll](https://jekyllrb.com/). What I want to know is how easy is it to do the following with Jekyll:

- Keep the website as it is
- When you go to youfirstpr.github.io/blog you see a list of posts
- Posts take this format: youfirstpr.github.io//blog/name-of-post on the website
- Blog posts are written in a `/posts` folder of this repository
- Blog posts are written in markdown and converted to .html so they can be rendered on the website
- Blog post can take the format 2015-12-10-your-first-pr.md

I know jekyll's strong point is to be a blogging platform, but write now all this repository does is serve static files.

I know that Hoodie manage to do this and would like to adopt a similar, if not simpler approach: https://github.com/hoodiehq/hood.ie


Does that make sense? Are you familiar with Jekyll?

**Comment by brad-j** [comment]
It does make sense and I'm familiar enough with Jekyll to get started. I've cloned the project and will get started! I'll use the hoodie site for reference.

**Comment by Charlotteis** [comment]
Awesome! Thank you for dedicating time to this little website :)

**Comment by brad-j** [comment]
Hi Charlotte!

I've got a page with a list of the blog posts and a page for each post. I've hit everything on the list. The styling is minimal (read: basically non-existent). 

I would love to keep going! What are your thoughts on perhaps using Sass?

Thanks for letting me work on this!

<img width="1154" alt="screenshot 2015-12-14 22 26 26" src="https://cloud.githubusercontent.com/assets/11680498/11801299/767e711c-a2b2-11e5-874b-5e014e493c3f.png">

<img width="1064" alt="screenshot 2015-12-14 22 30 27" src="https://cloud.githubusercontent.com/assets/11680498/11801328/ac271882-a2b2-11e5-87d9-fc4dc9333723.png">

**Comment by brad-j** [comment]
There's a little bug with the author name on the list of posts page. :-) I'm working on it.

**Comment by nickcolley** [comment]
@brad-j feel free to get a WIP PR in, can help out with the review if you do that :+1: 

No need to use Sass here since it's so simple I think.

**Comment by Charlotteis** [comment]
Wow @brad-j, this is phenomenal. Really and truly, thank you. I wish I could high five you.
What are your reasons for using Sass? I'm happy to consider it, I use Sass all the time, I just would like to check the WHY before we make any moves on that.

:sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles:

**Comment by Charlotteis** [comment]
And thank you @nickcolley for offering help too \o/

**Comment by brad-j** [comment]
No real pragmatic reason I guess (if the site continues to grow I can see a pragmatic benefit). It's just easier for me to wrap my head around Sass (oddly enough). Being able to break things out into little 'component' type things makes sense to me.

With that said, this is the first project I've ever worked so I could very well be getting ahead of myself.

**Comment by Charlotteis** [comment]
Hey @brad-j! I totally get what you mean. Right now, I'm going to say no as Sass is another barrier to entry for those who are unfamiliar with it. And due to the size of the project (so tiny!) we do not need it right now. I am totally going to revisit this in the future though :)

**Comment by Charlotteis** [comment]
Hey @brad-j, hows it going? Absolutely no rush to get this done, but I'd love to see what you've come up with / help with anything.

**Comment by robjloranger** [comment]
Not much happening here, what's the status? Do you still need help? I use Jekyll for my site.

**Comment by robjloranger** [comment]
Quick update: Almost done with implementing this. Just tweaking styling a bit. Will write a quick first post to include in the PR.

**Comment by Charlotteis** [comment]
This has been completed :)
