### ISSUE TITLE
http-crawler

### ISSUE THREAD

**Issue by inglesp** [yourfirstpr/yourfirstpr.github.io#46]
I've just put together [http-crawler](https://github.com/inglesp/http-crawler), a simple library for crawling websites with Python.  It does enough to meet my own immediate needs, but there are a handful of enhancements that could make it more useful.  I've listed these on the [issue tracker](https://github.com/inglesp/http-crawler/issues).

I'd be delighted if somebody who was new to Open Source would like to take these on, and I'd be happy to provide any mentoring or support required.

**Comment by sourabhtk37** [comment]
@inglesp Hey,I am available.(I am a beginner). :)

**Comment by inglesp** [comment]
Hi @sourabhtk37.  Would you like to take a look at https://github.com/inglesp/http-crawler/issues/6, and let me know if you think it's something you can have a go at?

**Comment by sourabhtk37** [comment]
I will try to solve issues first(so as to understand) then move on to adding features.

**Comment by djubreel** [comment]
Hello @inglesp I'm a beginner with python also, I'd love to try out a few new things

**Comment by inglesp** [comment]
Hi @djubreel.  Would you like to take a look at https://github.com/inglesp/http-crawler/issues/3?  Let me know if you'd to talk about what a fix might look like.

**Comment by mei-li** [comment]
Hello @inglesp, are you still working on this project? If so I would like to help if there is sth.

**Comment by inglesp** [comment]
Hi @mei-li.  Would you like to take a look at https://github.com/inglesp/http-crawler/issues/6?

**Comment by ars3nal** [comment]
Hey, i would like to work on something related to webscrapping. Are you still working on this projects? 
I'll go ahead and take a look at the issues,

**Comment by Supahupe** [comment]
Hi @inglesp , are you still interested in support to add new enhancements to http-crawler? I am interested in supporting your project.

**Comment by inglesp** [comment]
Hi @Supahupe -- I'm afraid I don't really have time to offer any help with this at the moment.  Thanks for your interest.
