### ISSUE TITLE
Automated first issue helpers

### ISSUE THREAD

**Issue by nickcolley** [yourfirstpr/yourfirstpr.github.io#5]
This might be a bit over thinking it but here it goes.

At the moment we can't just publish a list of github issues with labels since they might not have great instructions so I was thinking we could automate the review.

1. Have a format that can be parsed that contains the ingredients needed for a good first issue
2. Build a service (think Travis etc) that can watch a repo's issues
3. Expose first timer issues in one place.

**Comment by Charlotteis** [comment]
This would be absolutely bloody amazing if this was ever a thing. I cannot state just how much this would be amazing. I don't know where to start with this, but I'd love to discuss this here.

**Comment by nickcolley** [comment]
I'm going to explore the issue formatting now. Will report back.

**Comment by nickcolley** [comment]
Ok I've made a prototype: https://github.com/nickcolley/yourfirstpr-issue-proto

At the moment I'm just checking for the following:

Does the issue have a title of 'Your First PR'.

If it does parse it for a steps (lists).

If it has steps then it's good, if it doesnt show a message.

What we could do with is defining more characteristics of a good issue to continue

**Comment by nickcolley** [comment]
Dumping some resources here:

- http://www.hanselman.com/blog/BringKindnessBackToOpenSource.aspx
- https://medium.com/@kentcdodds/first-timers-only-78281ea47455

**Comment by Charlotteis** [comment]
Paging @mcmillan who seems to want to get involved!

**Comment by nickcolley** [comment]
Think this was over thought at this point.

**Comment by Charlotteis** [comment]
@nickcolley I take it this is something you do not want to do?

**Comment by nickcolley** [comment]
Just not sure it's a good idea.

**Comment by Charlotteis** [comment]
Ok. Well thank you anyway. :+1:
