### ISSUE TITLE
Add a Pull Request Template

### ISSUE THREAD

**Issue by Charlotteis** [yourfirstpr/yourfirstpr.github.io#58]
Following this guide: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

I'd love to have a PULL_REQUEST_TEMPLATE.md that looks something like:

```
Thanks so much for opening a pull request! Please provide the following information to help
the pull request reviewer merge your PR quicker!

## Explanation of Changes

Explanation goes here!

## Screenshot of Changes

Screenshot goes here!
```

Good use of emoji would be awesome, too! :D

**Comment by codeavenger07** [comment]
May I claim this? 👍
