### ISSUE TITLE
Your first PR steps

### ISSUE THREAD

**Issue by nickcolley** [yourfirstpr/yourfirstpr.github.io#6]
I was thinking, we sometimes have issues where you want it to be a first timer only issue but don't have the time for steps.

We could showcase these issues, it could even be someone's first contribution to open source!

**Comment by Charlotteis** [comment]
This is interesting! How do you see this working? :)

**Comment by nickcolley** [comment]
I was thinking this could be a biproduct of something like https://github.com/yourfirstpr/yourfirstpr.github.io/issues/5 but figured it should have it's own issue.
