### ISSUE TITLE
Valentina: EASY! Fix typo

### ISSUE THREAD

**Issue by slspencer** [yourfirstpr/yourfirstpr.github.io#73]
Replace all occurrences of 'allowence' with 'allowance'.
Fantastic easy for 1st pull request.
Valentina is written in C++ and uses Qt 5.7+ as the development environment. Qt makes building, testing, & debugging easy.
We have supportive developers and community for all of your questions.
Join our forum and introduce yourself! [http://forum.valentina-project.org](http://forum.valentina-project.org)
The repo is in Bitbucket and uses Mercurial (hg).
Issue #616:
[https://bitbucket.org/dismine/valentina/issues/616/code-typo-allow-e-nce-instead-of-allow-a](https://bitbucket.org/dismine/valentina/issues/616/code-typo-allow-e-nce-instead-of-allow-a)

**Comment by slspencer** [comment]
![typoallowence](https://cloud.githubusercontent.com/assets/578399/22186205/7d0f5a0c-e0b7-11e6-927d-81941da02d46.PNG)

**Comment by igormp** [comment]
I believe it should be closed since it has been already solved in the bitbucket repo

**Comment by slspencer** [comment]
Thanks Igor!

**Comment by slspencer** [comment]
Closed issue
