### ISSUE TITLE
404 Page Creation Required

### ISSUE THREAD

**Issue by Superari15** [yourfirstpr/yourfirstpr.github.io#95]
I need a good 404 page for my website - https://github.com/Superari15/funari/issues/1,

**Comment by vattytrivedi** [comment]
### Here are few best 404 pages from the [Codepen](https://codepen.io/saransh/pen/aezht).
- https://codepen.io/saransh/pen/aezht 
- https://codepen.io/marcobiedermann/pen/WbGazL?q=+404+page.&limit=all&type=type-pens
- https://codepen.io/kborling/pen/QwbKEe?q=+404+page.&limit=all&type=type-pens
- https://codepen.io/mycnlz/pen/LNbwwj?limit=all&page=2&q=+404+page.
- https://codepen.io/benstanley/pen/JYepog?limit=all&page=2&q=+404+page.

You can find more from the codepen itself

**Comment by pernambucano** [comment]
The issue is closed in the original [repo.](https://github.com/Superari15/funari/issues/1) Shouldn't we close this as well?

**Comment by Superari15** [comment]
Yes.
On 01-Dec-2017, at 7:41 AM, Paulo Fernandes <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is closed in the original repo.<https://github.com/Superari15/funari/issues/1> Shouldn't we close this as well?

**Comment by parthpandyappp** [comment]
I'll be very glad to contribute here.
